#!/bin/sh

if [ -z "$1" ]
then
    echo "Usage: $0 swagger|web|api"
else
        if [ "$1" = "swagger" ]
        then
            swagger project edit cjs-swagger
        fi
        if [ "$1" = "www" ]
        then
            cd cjs-www && lein figwheel
        fi
        if [ "$1" = "api" ]
        then
            cd cjs-api && lein ring server
        fi
fi
